# Generated by Django 3.0.8 on 2020-07-30 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_ngo_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ngo_details',
            old_name='p_address',
            new_name='ngo_address',
        ),
        migrations.RenameField(
            model_name='ngo_details',
            old_name='p_pincode',
            new_name='ngo_pincode',
        ),
    ]
