# Generated by Django 3.0.8 on 2020-07-31 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20200730_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccine_details',
            fields=[
                ('v_id', models.AutoField(primary_key=True, serialize=False)),
                ('v_name', models.CharField(max_length=500)),
                ('v_description', models.CharField(max_length=500)),
                ('max_dose_number', models.IntegerField()),
            ],
            options={
                'db_table': 'vaccine_details',
            },
        ),
        migrations.CreateModel(
            name='Vaccine_master',
            fields=[
                ('vm_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_id', models.IntegerField()),
                ('v_name', models.CharField(max_length=200)),
                ('days_after_birth', models.IntegerField()),
                ('next_visit', models.IntegerField()),
                ('gap_after_previous_vaccine', models.IntegerField()),
                ('v', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Vaccine_details')),
            ],
            options={
                'db_table': 'vaccine_master',
            },
        ),
        migrations.CreateModel(
            name='Vaccine_trx',
            fields=[
                ('v_trx_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_id', models.IntegerField()),
                ('date_of_vaccine', models.DateField()),
                ('next_vaccine_date', models.DateField()),
                ('dose_late_by', models.IntegerField()),
                ('c', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Child_details')),
                ('vm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Vaccine_master')),
            ],
            options={
                'db_table': 'vaccine_trx',
            },
        ),
        migrations.CreateModel(
            name='Upcoming_vaccine',
            fields=[
                ('u_id', models.AutoField(primary_key=True, serialize=False)),
                ('c', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Child_details')),
                ('date_of_vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Vaccine_trx')),
                ('vm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Vaccine_master')),
            ],
            options={
                'db_table': 'upcoming_vaccine',
            },
        ),
    ]
