# Generated by Django 3.0.8 on 2020-07-31 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_upcoming_vaccine_vaccine_details_vaccine_master_vaccine_trx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccine_trx',
            name='dose_late_by',
        ),
    ]
