# Generated by Django 3.0.8 on 2020-07-25 06:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HWRegister',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hwfname', models.CharField(max_length=50)),
                ('hwlname', models.CharField(max_length=50)),
                ('hwgender', models.CharField(default=True, max_length=50)),
                ('hwdob', models.DateField(default=datetime.date(2020, 7, 25))),
                ('hwemailid', models.EmailField(max_length=254)),
                ('hwmobileno', models.IntegerField()),
                ('hwpassword', models.CharField(max_length=64)),
                ('hwaddress', models.TextField()),
                ('hwpincode', models.IntegerField()),
                ('state', models.CharField(default='Null', max_length=50)),
                ('city', models.CharField(default='Null', max_length=50)),
            ],
        ),
    ]
