# Generated by Django 3.0.8 on 2020-07-25 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hwregister',
            name='hwmobileno',
            field=models.CharField(max_length=15),
        ),
    ]
