# Generated by Django 3.0.8 on 2020-07-25 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0002_auto_20200725_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anganwadi_details',
            fields=[
                ('aw_id', models.AutoField(primary_key=True, serialize=False)),
                ('aw_name', models.CharField(max_length=500)),
                ('aw_contact1', models.CharField(max_length=10, unique=True)),
                ('aw_contact2', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('aw_address', models.CharField(max_length=500)),
                ('aw_pincode', models.CharField(max_length=6)),
                ('aw_city', models.CharField(max_length=200)),
                ('aw_state', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'anganwadi_details',
            },
        ),
    ]
