# Generated by Django 3.0.8 on 2020-07-25 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0003_anganwadi_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anganwadi_details',
            name='aw_city',
            field=models.CharField(default='Null', max_length=50),
        ),
        migrations.AlterField(
            model_name='anganwadi_details',
            name='aw_state',
            field=models.CharField(default='Null', max_length=50),
        ),
    ]
