# Generated by Django 3.0.8 on 2020-07-26 16:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0004_auto_20200725_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hwregister',
            name='hwdob',
            field=models.DateField(default=datetime.date(2020, 7, 26)),
        ),
    ]
