# Generated by Django 3.0.8 on 2020-07-29 18:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0005_auto_20200726_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hwregister',
            name='hwdob',
            field=models.DateField(default=datetime.date(2020, 7, 30)),
        ),
    ]
