# Generated by Django 3.0.8 on 2020-07-31 20:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0006_auto_20200730_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hwregister',
            name='hwdob',
            field=models.DateField(default=datetime.date(2020, 8, 1)),
        ),
    ]
